In [2]:
import numpy as np
import random
from keras.layers import LSTM, Dense, Activation, Input, Lambda, Concatenate
from keras.models import Model
from keras import backend as K
from keras.optimizers import Adam
from collections import deque

## Make synthetic problem

In [44]:
len_sample = 8
dims = 16
n_samples = 200
documents, summaries = [], []

for i in range(n_samples):
    document, summary = [], []
    for j in range(len_sample):
        rnd = random.randint(0, 1)
        if rnd == 0:
            s = np.zeros((dims,)) #np.random.normal(loc = 0., scale = 0.2, size = (dims,))
            document.append(s)
        else:
            s = np.ones((dims,)) #np.random.normal(loc = 1, scale = 0.1, size = (dims,))
            document.append(s)
            summary.append(s)
            
    documents.append(document)
    summaries.append(summary)
    
documents = np.array(documents)
summaries = np.array(summaries)

## Actor Critic Agent

In [45]:
class A2CAgent:
    
    def __init__(self, doc_state_dim, summ_state_dim, action_dim = 2):
        
        self.doc_state_dim = doc_state_dim
        self.summ_state_dim = summ_state_dim
        self.action_dim = action_dim
        
        self.discount_factor = 0.99
        self.actor_lr = 0.001
        self.critic_lr = 0.005
  
        self.exploration_max = 1.0
        self.exploration_min = 0.01
        self.exploration_decay = 0.9995
        self.exploration_rate = self.exploration_max
        
        self.memory = deque(maxlen=MEMORY_SIZE)
        
        self.lstm_dims = 16
        self.reader, self.actor, self.critic = self.build_models()

        
    def build_models(self):
        
        doc_state = Input(shape=(None, dims))
        summ_state = Input(shape=(None, dims))
        state_h = Input(shape=(self.lstm_dims,))
        state_c = Input(shape=(self.lstm_dims,))
        
        lstm = LSTM(self.lstm_dims, activation = "tanh", name = "lstm_1", return_sequences=False, return_state=True)
        
        o1, lstm_state_h, lstm_state_c  = lstm(doc_state, initial_state = [state_h, state_c])
        o2, _, _  = lstm(summ_state, initial_state = [state_h, state_c])
    
        diff = Lambda(lambda x: K.abs(x[0] - x[1]))([o1, o2])
        diff = Concatenate()([o1, o2, diff])
        
        # Shared actor and critic #
        actor_output = Dense(self.action_dim, activation = "softmax")(diff)
        critic_output = Dense(1, activation="linear")(diff)
        
        reader = Model(inputs = [doc_state, state_h, state_c], outputs = [lstm_state_h, lstm_state_c])
        actor = Model(inputs = [doc_state, summ_state, state_h, state_c], outputs = actor_output)
        critic = Model(inputs = [doc_state, summ_state, state_h, state_c], outputs = critic_output)

        actor.compile(loss='categorical_crossentropy', optimizer=Adam(lr=self.actor_lr))
        critic.compile(loss="mse", optimizer=Adam(lr=self.critic_lr))
                       
        return reader, actor, critic
                        

    # using the output of policy network, pick action stochastically
    def get_action(self, doc_state, summ_state, state_h, state_c):
        if np.random.rand() < self.exploration_rate:
            return random.randrange(self.action_dim)
        policy = self.actor.predict([doc_state, summ_state, state_h, state_c])[0]
        r = np.random.choice(self.action_dim, 1, p=policy)[0]
        return r

                       
    def remember(self, doc_state, summ_state, state_h, state_c, 
                 action, reward, next_doc_state, next_summ_state, 
                 done):
        
        self.memory.append((doc_state, summ_state, state_h, state_c,
                            action, reward, next_doc_state, next_summ_state,
                            done)) 
     
    # update policy network every episode (Memory Replay & Batchified)
    def train_model(self):
        if len(self.memory) < MEMORY_SIZE:
            return
        
        target = np.zeros(1,)
        advantage = np.zeros((self.action_dim,))
        
        rnd_idx = random.randint(0, len(self.memory)-1)
        (doc_state, summ_state, state_h, state_c,
        action, reward, next_doc_state, next_summ_state,
        done)= self.memory[rnd_idx]
        summ_state = np.array([summ_state])
        next_summ_state = np.array([next_summ_state])

        values = self.critic.predict([doc_state, summ_state, state_h, state_c])[0]     
        next_values = self.critic.predict([next_doc_state, next_summ_state, state_h, state_c])[0]
              
        
        for i in range(1):
            if done:
                advantage[action] = max(min(1., reward - values), 0.)
                target[0] = reward
            else:
                # Explicacion: https://lilianweng.github.io/lil-log/2018/05/05/implementing-deep-reinforcement-learning-models.html#actor-critic
                advantage[action] = max(min(1., reward + self.discount_factor * (next_values) - values), 0.)
                target[0] = reward + self.discount_factor * next_values
                
        self.exploration_rate *= self.exploration_decay
        self.exploration_rate = max(self.exploration_min, self.exploration_rate)
        
        advantage = np.array([advantage])
        target = np.array([target])

        self.actor.fit([doc_state, summ_state, state_h, state_c], advantage, epochs=1, batch_size = 1, verbose=0)
        self.critic.fit([doc_state, summ_state, state_h, state_c], target, epochs=1, batch_size = 1, verbose=0)

In [46]:
def get_reward(gen_summary, summary):
    acum_sims = 0.
    for i in range(len(gen_summary)):
        found = False
        for j in range(len(summary)):
            if (gen_summary[i] == summary[j]).all() == True:
                found = True
                break
        if found == True:
            acum_sims += 1
        else:
            acum_sims -= 1
    return acum_sims #/ max(len(gen_summary), len(summary))

In [48]:
EPISODES = 10
N_SAMPLES = n_samples
BATCH_SIZE = 1
MEMORY_SIZE = 1024

# get size of state and action from environment
doc_state_dim = summ_state_dim = dims
action_dim = 2

# make A2C agent
agent = A2CAgent(doc_state_dim, summ_state_dim, action_dim)


for e in range(EPISODES):

    scores = []
    
    for i in range(N_SAMPLES):
        document = documents[i]
        summary = summaries[i]
        
        # Leer doc por completo #
        init_c_state = np.zeros((1, 16)) + 1e-16
        init_h_state = np.zeros((1, 16)) + 1e-16
        lstm_h_state, lstm_c_state = agent.reader.predict([np.array([document]), init_h_state, init_c_state])

        summ_state = [np.zeros(summ_state_dim) + 1e-16]
        actions = []

        for j in range(len(document)):

            doc_state = np.array([document[0 : j + 1]])
            next_doc_state = np.array([document[0 : j + 2]])
            next_summ_state = summ_state[:]

            action = agent.get_action(doc_state, np.array([summ_state]), lstm_h_state, lstm_c_state)
            
            if action == 1:
                next_summ_state.append(document[j].tolist())
                actions.append(1)
            else:
                actions.append(0)

            reward = get_reward(np.array(next_summ_state[1:]), summary)

            if j < len(document) - 1:
                done = False
            else:
                done = True

            agent.remember(doc_state, summ_state, lstm_h_state, lstm_c_state, 
                           action, reward, next_doc_state, next_summ_state, done)

            agent.train_model()

            summ_state = next_summ_state
        scores.append(reward)
        #print("Sample: %d, Actions: %s, Reward: %.4f" % (i, str(actions), reward))
    print("Avg reward on episode: %d -> %.3f" % (e, np.array(scores).mean()))

Avg reward on episode: 0 -> 0.160
Avg reward on episode: 1 -> 0.750
Avg reward on episode: 2 -> 1.725
Avg reward on episode: 3 -> 2.095
Avg reward on episode: 4 -> 2.125
Avg reward on episode: 5 -> 2.400
Avg reward on episode: 6 -> 2.910
Avg reward on episode: 7 -> 2.860
Avg reward on episode: 8 -> 3.145
Avg reward on episode: 9 -> 3.490


In [49]:
document = documents[1]
summary = summaries[1]

# Leer doc por completo #
init_c_state = np.zeros((1, 16)) + 1e-16
init_h_state = np.zeros((1, 16)) + 1e-16
lstm_h_state, lstm_c_state = agent.reader.predict([np.array([document]), init_h_state, init_c_state])

summ_state = [np.zeros(summ_state_dim) + 1e-16]
actions = []

for j in range(len(document)):

    doc_state = np.array([document[0 : j + 1]])
    next_doc_state = np.array([document[0 : j + 2]])
    next_summ_state = summ_state[:]

    action = agent.get_action(doc_state, np.array([summ_state]), lstm_h_state, lstm_c_state)

    if action == 1:
        next_summ_state.append(document[j].tolist())
        actions.append(1)
    else:
        actions.append(0)

    reward = get_reward(np.array(next_summ_state[1:]), summary)

    if j < len(document) - 1:
        done = False
    else:
        done = True
    
    summ_state = next_summ_state

In [50]:
actions

[0, 1, 1, 0, 0, 0, 1, 1]

In [51]:
document

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
summary

[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])]

In [53]:
np.array(summ_state[1:])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [43]:
get_reward(summ_state[1:], summary)

2.0